CREATE TABLE TEMP_MAP(
   ID_LOCAL INT,
   NOM VARCHAR(50)  NOT NULL,
   PRIMARY KEY(ID_LOCAL)
);

CREATE TABLE MAP_LOCALISATION(
   ID_MAP VARCHAR(50) ,
   LATITUDE DOUBLE,
   LONGITUDE DOUBLE,
   PRIMARY KEY(ID_MAP)
);

CREATE TABLE TROLLEY(
   ID_ARDUINO INT,
   NOM_TROLLEY VARCHAR(50)  NOT NULL,
   LIGNE VARCHAR(50)  NOT NULL,
   DATE_PROD VARCHAR(50)  NOT NULL,
   LIVRER VARCHAR(50)  NOT NULL,
   CONSOMMER VARCHAR(50)  NOT NULL,
   STATUT VARCHAR(50) ,
   ID_MAP VARCHAR(50)  NOT NULL,
   PRIMARY KEY(ID_ARDUINO),
   FOREIGN KEY(ID_MAP) REFERENCES MAP_LOCALISATION(ID_MAP)
);

CREATE TABLE TEMPERATURE(
   ID_TEMPERATURE INT,
   TEMPERATURE DECIMAL(5,2)  ,
   HUMIDITE DECIMAL(5,2)  ,
   TENSION DECIMAL(5,2)  ,
   T_RESSENTIE DECIMAL(5,2)  ,
   DATE_TEMP DATETIME,
   ID_LOCAL INT NOT NULL,
   ID_ARDUINO INT NOT NULL,
   PRIMARY KEY(ID_TEMPERATURE),
   FOREIGN KEY(ID_LOCAL) REFERENCES TEMP_MAP(ID_LOCAL),
   FOREIGN KEY(ID_ARDUINO) REFERENCES TROLLEY(ID_ARDUINO)
);
